os:
  - linux

branches:
  only:
  - master

language: generic

services:
  - docker
env:
  global:
    - REPO_NAME=pyhyp
    - DOCKER_WORKING_DIR=/home/mdolabuser/repos/$REPO_NAME
    - DOCKER_MOUNT_DIR=/home/mdolabuser/travis/$REPO_NAME
  jobs:
    - DOCKER_TAG=c7-gcc-ompi-latest
    - DOCKER_TAG=c7-intel-impi-latest
    - DOCKER_TAG=u18-gcc-ompi-latest
    - DOCKER_TAG=u18-gcc-ompi-stable
    - DOCKER_TAG=u20-gcc-ompi-latest
    - DOCKER_TAG=u20-gcc-ompi-stable

before_install:
  - docker pull mdolab/public:$DOCKER_TAG
  # run Docker, key is we mount the current Travis directory into Docker to access content of repo
  - docker run -t -d 
        --name app
        --mount "type=bind,src=$(pwd),target=$DOCKER_MOUNT_DIR"
        mdolab/public:$DOCKER_TAG
        /bin/bash

install:
  # We thrown away the existing repo in Docker, and copy the new one in-place
  - docker exec -it app /bin/bash -c "rm -rf $DOCKER_WORKING_DIR && cp -r $DOCKER_MOUNT_DIR $DOCKER_WORKING_DIR"
  # Copy over the correct config file and modify as needed
  - if [[ "$DOCKER_TAG" == *"intel"* ]]; then
      docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && cp config/defaults/config.LINUX_INTEL_OPENMPI.mk config/config.mk";
    else
      docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && cp config/defaults/config.LINUX_GFORTRAN_OPENMPI.mk config/config.mk";
      if [[ "$DOCKER_TAG" == *"py2"* ]]; then
        docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && sed -i 's/python3-config/python-config/g' config/config.mk";
      fi
    fi
  # Compile
  - docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && make && pip install ."

  # the version of testflo is too new, we downgrade to the last version that supports py2
  - docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && pip install testflo==1.3.5 "

script:
  # We need to source the mdolab bashrc before running anything
  - docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR && testflo . -v -n 1"
  # check that new CGNS files have been generated
  - docker exec -it app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd $DOCKER_WORKING_DIR/examples && ls -l */*.cgns"

after_script:
  - docker rm -f app
