import:
  - mdolab/.github:travis-env.yml
  - mdolab/.github:travis-before-install.yml
  - mdolab/.github:travis-install.yml

env:
  global:
    - DOCKER_REPO=public
    - GCC_CONFIG=config/defaults/config.LINUX_GFORTRAN_OPENMPI.mk
    - INTEL_CONFIG=config/defaults/config.LINUX_INTEL_OPENMPI.mk

script:
  # We need to source the mdolab bashrc before running anything
  - docker exec -it app /bin/bash -c ". $BASHRC && cd $DOCKER_WORKING_DIR && testflo . -v -n 1"
  # check that new CGNS files have been generated
  - docker exec -it app /bin/bash -c ". $BASHRC && cd $DOCKER_WORKING_DIR/examples && ls -l */*.cgns"

after_script:
  - docker rm -f app
