import:
  - mdolab/.github:travis/jobs-env.yml
  - mdolab/.github:travis/before-install.yml
  - mdolab/.github:travis/install.yml
  - mdolab/.github:travis/script.yml

env:
  global:
    - DOCKER_REPO=public
    - GCC_CONFIG=config/defaults/config.LINUX_GFORTRAN_OPENMPI.mk
    - INTEL_CONFIG=config/defaults/config.LINUX_INTEL_OPENMPI.mk

script:
  # check that new CGNS files have been generated
  - if [[ "$TEST_TYPE" == "docker" ]]; then
      docker exec -it app /bin/bash -c ". $BASHRC && cd $DOCKER_WORKING_DIR && testflo . -v -n 1";
      docker exec -it app /bin/bash -c ". $BASHRC && cd $DOCKER_WORKING_DIR/examples && ls -l */*.cgns";
    fi

after_script:
  - docker rm -f app
